### ISSUE TITLE
[BUG]hyzmtf配置里面的tankfight插件不会传送生还

### ISSUE THREAD

**Issue by NanakaFathry** [PencilMario/L4D2-Competitive-Rework#81]
sm plugins load optional/l4d_tankfight.smx
坦克死亡后生还全部扶起来不会传送进安全屋

**Comment by PencilMario** [comment]
~~居然有人玩这个插件~~
传送安全屋我偷懒了，用的[这个](https://github.com/PencilMario/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/safearea_teleport.sp)插件，要把这个也加载了才有用

**Comment by NanakaFathry** [comment]
有确保加载了这个safearea_teleport插件，也尝试调节前后加载顺序仍然不会在克死亡后触发传送生还进屋

**Comment by NanakaFathry** [comment]
好奇怪o 是bug嘛

**Comment by PencilMario** [comment]
safearea_teleport应该有gamedata的 后台sm plugins list看一下有没有报错 也试试手动用指令sm_warpend 如果没进安全屋就是safearea_teleport的问题

**Comment by NanakaFathry** [comment]
> safearea_teleport应该有gamedata的 后台sm plugins list看一下有没有报错 也试试手动用指令sm_warpend 如果没进安全屋就是safearea_teleport的问题

插件全部正常加载 没有报错 safearea_teleport 的 gamedata也有放进去的 safearea_teleport 有正常加载上去

**Comment by PencilMario** [comment]
已修复

**Comment by NanakaFathry** [comment]
试了一下现在可以成功传送安全门了，又有tankfight可以玩了 谢谢bro~很喜欢这个模式

**Comment by NanakaFathry** [comment]
目前已知发现一些小问题 就是tank生成在太靠后或太靠前的路程时会导致生还坦克传送同一位置 可能需要后续细调ban掉一些坦克点位来解决 
![d500b86be26852a66fab2f30e2b5f97a](https://github.com/PencilMario/L4D2-Competitive-Rework/assets/108194610/537d0115-c99b-4b54-8e10-7cc9ac2121b2)

（如图克所在位置非常尴尬，生还直接集火逃都逃不掉  这时特感还活不了）

**Comment by NanakaFathry** [comment]
像c5m2 56以及之后的路程得ban掉 不然克跟生还传送一块

**Comment by PencilMario** [comment]
是这样 还有c3m1 如果克的点位在机关后会不刷克 c2m5有时候刷的距离也会比较近
我有时间想一下这块怎么处理吧
